### PR TITLE
Convert jbuild to dune files

### PR DESCRIPTION
**Pull request by rgrinberg**
Automatically done with dune upgrade

### CODE REVIEW

**Comment by rgrinberg** [comment]
Would it be possible to make a release with this fix please :)

The issue is that jbuild files are no longer going to be accepted in dune 2.0

**Comment by aantron** [comment]
Yes, I will do a release. Thanks!

**Comment by aantron** [comment]
https://github.com/ocaml/opam-repository/pull/14610

**Comment by aantron** [comment]
I'll do the upgrade in Lwt_glib and Lwt_ssl.

**Pull request merged**
